### ISSUE TITLE
OpenCV error on Fedora 37

### ISSUE THREAD

**Issue by aleksify** [joschuck/matrix-webcam#9]
Installed using `pip install matrix-webcam` (without `sudo`), ran with `matrix-webcam`, got green terminal with this error:
```
Traceback (most recent call last):
  File "/home/alex/.local/bin/matrix-webcam", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alex/.local/lib/python3.11/site-packages/matrix_webcam/__main__.py", line 55, in main
    print(ascii_image(image, args.width, args.height))  # ascii image
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.local/lib/python3.11/site-packages/matrix_webcam/__main__.py", line 13, in ascii_image
    image = cv2.resize(image, (width, height))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

Some info:
`pip 22.2.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)`
`Python 3.11.0rc2`

**Comment by joschuck** [comment]
i see you are using a release candidate version of Python 3.11, can you try with Python 3.10 and check if opencv 4.5.x will be installed?

**Comment by aleksify** [comment]
@joschuck it's working with Python 3.10.
